// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCzXcXqJY5uM8Hotrz97crQ1o1Fs8H67o',
    appId: '1:804025404936:web:60b4038323f692b4ae0bbd',
    messagingSenderId: '804025404936',
    projectId: 'mashal-449f5',
    authDomain: 'mashal-449f5.firebaseapp.com',
    storageBucket: 'mashal-449f5.appspot.com',
    measurementId: 'G-W1Z6PCNHNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMvS3acADe6jjcmSmwh_spVJeQj9gRkFM',
    appId: '1:804025404936:android:7695eadfaf6f159bae0bbd',
    messagingSenderId: '804025404936',
    projectId: 'mashal-449f5',
    storageBucket: 'mashal-449f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGf4NphmIQCEbgbw1CmqHNLnftIBd0AVg',
    appId: '1:804025404936:ios:902fd346b998810cae0bbd',
    messagingSenderId: '804025404936',
    projectId: 'mashal-449f5',
    storageBucket: 'mashal-449f5.appspot.com',
    iosClientId: '804025404936-r3mke2jpafq6mnml211m6q3g8te415ub.apps.googleusercontent.com',
    iosBundleId: 'com.example.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGf4NphmIQCEbgbw1CmqHNLnftIBd0AVg',
    appId: '1:804025404936:ios:dc389ec104c5bebaae0bbd',
    messagingSenderId: '804025404936',
    projectId: 'mashal-449f5',
    storageBucket: 'mashal-449f5.appspot.com',
    iosClientId: '804025404936-mpr7i7buj6favj483894ietbv1ke6egp.apps.googleusercontent.com',
    iosBundleId: 'com.example.customer.RunnerTests',
  );
}
